// Base de datos de canciones
const tracks = [
    {
        id: 1,
        title: "El Pionero de tu Amor",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/El pionero de tu amor.mp3",
        coverImage: "portada/El pionero de tu amor.png",
        coverGradient: "from-sky-400 via-cyan-500 to-blue-600",
        dedication: "A menudo perdemos mucho tiempo tratando de etiquetar lo inefable. Nos desgastamos preguntándonos: ¿Será esto amor? ¿O será simplemente una ilusión, un truco de la mente para no sentirse sola? Y es válido tener dudas. La mente duda, siempre duda. Pero el cuerpo... el cuerpo no sabe mentir. Hay una frase que resuena mucho en mí últimamente y es que, contigo, me he vuelto un pionero. Y ojo, no un pionero porque sea el primero en amar en la historia de la humanidad, sino porque contigo estoy descubriendo territorios emocionales que yo no sabía que existían en mí. Soy el primer hombre en pisar este sentimiento específico que tú provocas. Porque cuando te veo, la lógica se rompe. Esa duda existencial sobre si \"es o no es amor\" se disuelve en el momento exacto en que mis ojos conectan con los tuyos y siento ese caos ordenado, esas mariposas, esa revolución interna. Así que, quizá no tenga la definición exacta de lo que somos en un diccionario... pero tengo la certeza de lo que siento. Y si ser un pionero significa explorar lo desconocido con miedo pero con emoción... entonces, gracias por darme el mapa para descubrirme a mí mismo, a través de ti.",
        emoji: "🧭",
        description: "Capítulo 1: El Pionero de tu Amor",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 2, text: "[Verso 1]" },
            { time: 6, text: "Me despierto y la duda viene a visitarme" },
            { time: 10, text: "camina por mi cuarto, intenta interrogarme." },
            { time: 14, text: "Me pregunta por qué tiemblo si escucho tu voz," },
            { time: 18, text: "si esto es para siempre o es cosa de dos." },
            { time: 22, text: "Miro al techo y busco una explicación," },
            { time: 26, text: "no sé si esto es amor" },
            { time: 30, text: "o si solo es una ilusión." },
            { time: 34, text: "[Pre-Coro]" },
            { time: 38, text: "Pero entonces llegas tú," },
            { time: 42, text: "y la lógica se apaga, se va la luz." },
            { time: 46, text: "Ya no importan las preguntas, ni el miedo," },
            { time: 50, text: "solo importa que estás aquí, y no me quedo quieto." },
            { time: 54, text: "[Coro]" },
            { time: 58, text: "Porque pasa que soy pionero" },
            { time: 62, text: "en descubrir mapas que no conocía," },
            { time: 66, text: "en sentir todo lo que siento" },
            { time: 70, text: "cada vez que tú me miras." },
            { time: 74, text: "Y es lo que pasa, cuando te veo" },
            { time: 78, text: "la gravedad se invierte, alzo el vuelo," },
            { time: 82, text: "y siento muchas mariposas" },
            { time: 86, text: "bailando por todo mi cuerpo," },
            { time: 90, text: "haciendo fiesta en mi pecho." },
            { time: 94, text: "[Verso 2]" },
            { time: 98, text: "Nunca antes nadie me hizo sentir así," },
            { time: 102, text: "como si el mundo empezara justo en ti." },
            { time: 106, text: "Antes de tu risa yo era un turista más," },
            { time: 110, text: "caminando sin rumbo, mirando hacia atrás." },
            { time: 114, text: "Pero ahora tengo una misión urgente:" },
            { time: 118, text: "quererte despacio, quererte fuerte." },
            { time: 122, text: "[Coro]" },
            { time: 126, text: "Porque pasa que soy pionero" },
            { time: 130, text: "en descubrir mapas que no conocía," },
            { time: 134, text: "en sentir todo lo que siento" },
            { time: 138, text: "cada vez que tú me miras." },
            { time: 142, text: "Y es lo que pasa, cuando te veo" },
            { time: 146, text: "la gravedad se invierte, alzo el vuelo," },
            { time: 150, text: "y siento muchas mariposas" },
            { time: 154, text: "bailando por todo mi cuerpo." },
            { time: 158, text: "[Puente]" },
            { time: 162, text: "Y si es una ilusión, que no me despierten," },
            { time: 166, text: "que este sueño es lo mejor que he tenido." },
            { time: 170, text: "Pero si es amor..." },
            { time: 174, text: "entonces soy el hombre más afortunado de haberte conocido." },
            { time: 178, text: "[Outro]" },
            { time: 182, text: "Sí... soy un pionero." },
            { time: 186, text: "Descubriendo el amor..." },
            { time: 190, text: "cuando te veo" },
            { time: 194, text: "Siento mariposas..." },
            { time: 198, text: "solo mariposas..." },
            { time: 202, text: "♪" }
        ],
        memories: []
    },
    {
        id: 2,
        title: "Si eres tú",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Si eres tú.wav",
        coverImage: "portada/Si Eres Tú.png",
        coverGradient: "from-pink-500 via-rose-500 to-red-500",
        dedication: "Vivimos en un universo que tiende naturalmente al caos, a la entropía, y entre tantas variables infinitas, la probabilidad de cruzarnos era casi nula. Sin embargo, sucediste. Si antes mi realidad era una secuencia monótona de grises, tu llegada funcionó como el prisma que necesitaba para entender la luz. Esta canción es la prueba de que, a veces, la vida no necesita ser perfecta para tener sentido; solo necesita a la persona correcta para tener color.",
        emoji: "💖",
        description: "Capítulo 2: Si eres tú",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 15, text: "[Verse 1]" },
            { time: 19, text: "Qué pensará tu papá" },
            { time: 23, text: "si se entera que su hija consentida se robó mis latidos" },
            { time: 29, text: "Y contarle a tu mamá" },
            { time: 33, text: "que ya tienes quien te sirva de refugio y te sirva de abrigo" },
            { time: 39, text: "Tienes esa forma de ser" },
            { time: 43, text: "que me gana cada vez que te acercas, cada que te miro" },
            { time: 49, text: "Tanto tiempo te soñé" },
            { time: 53, text: "y hoy por fin te tengo..." },
            { time: 57, text: "" },
            { time: 58, text: "[Chorus]" },
            { time: 59, text: "No podría dejarte..." },
            { time: 63, text: "si solo con mirarte..." },
            { time: 67, text: "mi gris deja de ser gris" },
            { time: 71, text: "y empieza a tener sentido" },
            { time: 75, text: "no podría dejarte..." },
            { time: 79, text: "¿cómo no enamorarme?" },
            { time: 83, text: "si eres tú" },
            { time: 86, text: "Si eres tú" },
            { time: 88, text: "si eres tú" },
            { time: 90, text: "Si eres tú" },
            { time: 92, text: "si eres tú quien le dió color a mi vida..." },
            { time: 97, text: "" },
            { time: 98, text: "[Verse 2]" },
            { time: 99, text: "Se lo digo a tu papá" },
            { time: 103, text: "que me diste la alegría que le falta a mis días vacíos" },
            { time: 109, text: "Y le explico a tu mamá" },
            { time: 113, text: "que sus rezos funcionaron pa' que cruces tu camino al mío" },
            { time: 119, text: "No hace falta nada más" },
            { time: 123, text: "porque todo lo que quiero lo tengo justo aquí contigo" },
            { time: 129, text: "Tanto tiempo lo soñé" },
            { time: 133, text: "y hoy aquí te tengo" },
            { time: 137, text: "" },
            { time: 138, text: "[Chorus]" },
            { time: 139, text: "No podría dejarte..." },
            { time: 143, text: "si solo con mirarte..." },
            { time: 147, text: "mi gris deja de ser gris" },
            { time: 151, text: "y empieza a tener sentido" },
            { time: 155, text: "no podría dejarte..." },
            { time: 159, text: "cómo no enamorarme?" },
            { time: 163, text: "si eres tú" },
            { time: 166, text: "Si eres tú" },
            { time: 168, text: "si eres tú" },
            { time: 170, text: "Si eres tú" },
            { time: 172, text: "si eres tú quien le dió color a mi vida..." },
            { time: 177, text: "" },
            { time: 178, text: "[Outro]" },
            { time: 179, text: "Si eres tú..." },
            { time: 183, text: "quien le da sentido" },
            { time: 187, text: "a mi vida." },
            { time: 191, text: "♪" }
        ]
    },
    {
        id: 3,
        title: "Mi cora... y más",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Mi cora... y más.wav",
        coverImage: "portada/Mi cora... y más.png",
        coverGradient: "from-orange-400 via-red-500 to-pink-500",
        dedication: "Vivimos en un universo de variables infinitas, donde la mayoría de las melodías son ruido de fondo, intercambiables y efímeras. Pero existen ciertas frecuencias que nacen con un propósito singular, diseñadas para resonar con una sola alma en toda la existencia. Esta canción no te la dedico; esta canción te pertenece por derecho ontológico. Lleva tu huella dactilar metafísica codificada en su ritmo y en el empeño que solo pensando en ti, pude completar. Es intransferible, porque para que alguien más pudiera reclamarla, tendría que suceder lo imposible: tendrían que ser tú.",
        emoji: "💝",
        description: "Capítulo 3: Mi cora... y más",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 6, text: "[Verse 1]" },
            { time: 8, text: "Perdona si vengo a buscarte así" },
            { time: 12, text: "No aguantaba más sin saber de ti" },
            { time: 16, text: "No traigo castillos ni falsa ilusión" },
            { time: 20, text: "Solo te ofrezco mi fiel corazón" },
            { time: 24, text: "" },
            { time: 24.5, text: "[Pre-Chorus]" },
            { time: 25, text: "Que sepa tu padre y también mamá" },
            { time: 29, text: "Que este loco te quiere con sinceridad" },
            { time: 33, text: "No busco aventuras vengo por tu amor" },
            { time: 37, text: "A cuidar por siempre de tu corazón" },
            { time: 41, text: "" },
            { time: 41.5, text: "[Chorus]" },
            { time: 42, text: "Porque tienes mi Cora" },
            { time: 45, text: "Y más que soñar" },
            { time: 47, text: "Tú tienes la magia de hacerme volar" },
            { time: 51, text: "Eres mi Cora" },
            { time: 53, text: "Y más mi verdad" },
            { time: 55, text: "Si me das un sí me voy a quedar" },
            { time: 59, text: "" },
            { time: 59.5, text: "[Verse 2]" },
            { time: 60, text: "Dicen que estamos muy chicos los dos" },
            { time: 64, text: "Pero esto es grande lo juro por Dios" },
            { time: 68, text: "El tiempo dirá que tengo razón" },
            { time: 72, text: "Que tú eres la dueña de mi devoción" },
            { time: 76, text: "" },
            { time: 76.5, text: "[Chorus]" },
            { time: 77, text: "Porque tienes mi Cora" },
            { time: 80, text: "Y más que soñar" },
            { time: 82, text: "Tú tienes la magia de hacerme volar" },
            { time: 86, text: "Eres mi Cora" },
            { time: 88, text: "Y más mi verdad" },
            { time: 90, text: "Si me das un sí me voy a quedar" },
            { time: 94, text: "" },
            { time: 94.5, text: "[Montuno]" },
            { time: 95, text: "Tú tienes mi Cora, y más... mucho más" },
            { time: 100, text: "Oye mi niña bonita, no te vayas jamás" },
            { time: 105, text: "Tú tienes mi Cora, y más... mucho más" },
            { time: 110, text: "Es que mi Cora... imagina todo lo que me das" },
            { time: 115, text: "Tú tienes mi Cora, y más... mucho más" },
            { time: 120, text: "Te vengo a robar, te vengo a adorar..." },
            { time: 124, text: "¡con respeto te voy a cuidar!" },
            { time: 128, text: "♪" }
        ],
        memories: []
    },
    {
        id: 4,
        title: "Fuera de Guion",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Fuera de guion.wav",
        coverImage: "portada/Fuera de guion.png",
        coverGradient: "from-amber-400 via-orange-500 to-red-500",
        dedication: "Nos pasamos la vida obsesionados con ser los autores de nuestro propio destino, creyendo que tener el control del guion es la única forma de evitar el caos. Sin embargo, las mejores historias no son las que se planean milimétricamente, sino las que se rompen por un giro inesperado. Tú fuiste ese plot twist en mi narrativa; la improvisación que no vi venir pero que terminó salvando la trama. Gracias por enseñarme que la vida no se trata de seguir un libreto perfecto, sino de encontrar a alguien con quien valga la pena salirse del guion.",
        emoji: "📖",
        description: "Capítulo 4: Fuera de Guion",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 5, text: "[Verse 1]" },
            { time: 8, text: "Yo era el rey del drama, el de la tinta gris" },
            { time: 12, text: "Escribiendo tragedias donde no era feliz." },
            { time: 16, text: "Tenía mi libreta llena de tachones" },
            { time: 20, text: "Buscando culpables, buscando razones." },
            { time: 24, text: "Mi vida era un libro de esos aburridos" },
            { time: 28, text: "De los que se quedan a medias, dormidos." },
            { time: 32, text: "" },
            { time: 34, text: "[Pre-Chorus]" },
            { time: 36, text: "Pero llegaste tú con ese resaltador" },
            { time: 40, text: "A cambiarme la letra, a cambiarme el color." },
            { time: 44, text: "No pediste permiso para editar" },
            { time: 48, text: "Lo que yo juraba que no iba a cambiar." },
            { time: 52, text: "Y le diste la vuelta a la página diez..." },
            { time: 56, text: "" },
            { time: 58, text: "[Chorus]" },
            { time: 60, text: "¡Y ahora no sigo el guion!" },
            { time: 64, text: "Me hiciste un plot twist en el corazón." },
            { time: 68, text: "Yo iba para el sur y tú me llevaste al norte" },
            { time: 72, text: "Rompiste mis esquemas, rompiste el soporte." },
            { time: 76, text: "No sé qué capítulo es, ni cómo termina" },
            { time: 80, text: "Pero es mi favorito si tú eres la heroína." },
            { time: 84, text: "" },
            { time: 86, text: "[Verse 2]" },
            { time: 88, text: "Mis amigos dicen: \"¿Qué le pasó al poeta?" },
            { time: 92, text: "Que ahora anda riendo, que rompió la careta\"." },
            { time: 96, text: "Es que contigo el drama ya no me combina" },
            { time: 100, text: "Tú eres comedia romántica y adrenalina." },
            { time: 104, text: "Borraste al villano, quitaste el dolor" },
            { time: 108, text: "Y ahora la trama me suena mejor." },
            { time: 112, text: "" },
            { time: 114, text: "[Chorus]" },
            { time: 116, text: "¡Y ahora no sigo el guion!" },
            { time: 120, text: "Me hiciste un plot twist en el corazón." },
            { time: 124, text: "Yo iba para el sur y tú me llevaste al norte" },
            { time: 128, text: "Rompiste mis esquemas, rompiste el soporte." },
            { time: 132, text: "No sé qué capítulo es, ni cómo termina" },
            { time: 136, text: "Pero es mi favorito si tú eres la heroína." },
            { time: 140, text: "" },
            { time: 142, text: "[Bridge]" },
            { time: 144, text: "Y si alguien pregunta de qué trata mi historia" },
            { time: 148, text: "Les digo que olviden mi vieja memoria." },
            { time: 152, text: "Que la historia empieza..." },
            { time: 156, text: "Justo cuando tú dices \"Hola\"." },
            { time: 160, text: "" },
            { time: 162, text: "[Solo de Guitarra]" },
            { time: 170, text: "" },
            { time: 172, text: "[Chorus Final]" },
            { time: 174, text: "¡Porque no sigo el guion!" },
            { time: 178, text: "Me hiciste un plot twist en el corazón." },
            { time: 182, text: "Yo iba para el sur y tú me llevaste al norte" },
            { time: 186, text: "Rompiste mis esquemas, rompiste el soporte." },
            { time: 190, text: "¡Quédate en la historia, no tenga final!" },
            { time: 194, text: "Contigo lo normal se vuelve genial." },
            { time: 198, text: "" },
            { time: 200, text: "[Outro]" },
            { time: 202, text: "Fuera de guion." },
            { time: 206, text: "Tú y yo." },
            { time: 210, text: "Mucho mejor así." },
            { time: 214, text: "♪" }
        ],
        memories: []
    },
    {
        id: 5,
        title: "One less lonely girl",
        artist: "Cover - Justin Bieber",
        type: "Cover",
        audioUrl: "audio/One less lonely girl.wav",
        coverImage: "portada/One less lonely girl.png",
        coverGradient: "from-purple-400 via-pink-500 to-red-500",
        dedication: "A veces pensamos que la soledad es un vacío, cuando en realidad es el espacio que la vida reserva para quien de verdad sabrá llenarlo. Sé que hubo historias antes, \"start overs\" y lágrimas que no debieron caer. Pero elegí cantarte esto para hacerte una promesa tangible: mientras dependa de mí, la soledad será solo un recuerdo borroso. Entre tantas opciones y ruido allá afuera, mis ojos decidieron enfocarse en una sola variable. Tú eres mi elección consciente para que, en este mundo, haya una chica solitaria menos y un amor verdadero más.",
        emoji: "💜",
        description: "Capítulo 5: One less lonely girl",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 5, text: "[Verse 1]" },
            { time: 8, text: "How many I told you's and start overs and shoulders have you cried on before?" },
            { time: 15, text: "How many promises, be honest girl, how many tears you let hit the floor?" },
            { time: 22, text: "How many bags you packed, just to take them back, tell me that, how many either ors?" },
            { time: 29, text: "But no more if you let me inside of your world, there'll be one less lonely girl" },
            { time: 36, text: "" },
            { time: 37, text: "[Pre-Chorus]" },
            { time: 38, text: "Oh, no, saw so many pretty faces" },
            { time: 43, text: "Now all I see is you" },
            { time: 46, text: "No, no, no, don't need these other pretty faces" },
            { time: 51, text: "And when you're mine in the world, there's gonna be one less lonely girl" },
            { time: 58, text: "" },
            { time: 59, text: "[Chorus]" },
            { time: 60, text: "One less lonely girl" },
            { time: 64, text: "One less lonely girl" },
            { time: 68, text: "One less lonely girl" },
            { time: 72, text: "♪" }
        ],
        memories: []
    },
    {
        id: 6,
        title: "Te voy a robar el corazón",
        artist: "Cover - Salserín",
        type: "Cover",
        audioUrl: "audio/Te voy a robar el corazón.wav",
        coverImage: "portada/Te voy a robar el corazón.png",
        coverGradient: "from-red-400 via-pink-500 to-rose-500",
        dedication: "Vivimos buscando la sanidad y el equilibrio, pero curiosamente, existen \"enfermedades\" como la que describe esta canción que son las únicas que nos hacen sentir verdaderamente vivos. Me declaro un caso clínico voluntario de este sentimiento. Y aunque la sociedad dice que robar es restar, en la física del amor, \"robarte el corazón\" es la única operación donde ambos salimos ganando. No vengo a quitarte nada, vengo a cuidarlo tanto que decidas dejarlo en mis manos, no por una eternidad incalculable, sino hasta donde la vida, el destino y nuestras ganas nos permitan llegar.",
        emoji: "❤️",
        description: "Capítulo 6: Te voy a robar el corazón",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 5, text: "[Verse 1]" },
            { time: 8, text: "Dicen que el amor es una enfermedad" },
            { time: 12, text: "Me declaro enfermo desde que tú estás" },
            { time: 16, text: "Dicen que los sueños se hacen realidad" },
            { time: 20, text: "No he parado de soñar nunca más" },
            { time: 24, text: "" },
            { time: 25, text: "[Pre-Chorus]" },
            { time: 26, text: "Y ahora que te vi, te quiero a ti" },
            { time: 30, text: "Y robando corazones, soñarás en mí" },
            { time: 34, text: "" },
            { time: 35, text: "[Chorus]" },
            { time: 36, text: "Yo voy a besarte, voy a cuidarte," },
            { time: 40, text: "Voy a robarte el corazón" },
            { time: 43, text: "Para que creas en mi amor" },
            { time: 46, text: "Yo quiero abrazarte y nunca dejarte" },
            { time: 50, text: "Voy a robarte el corazón" },
            { time: 53, text: "Y te enamores como yo, loco de ilusión" },
            { time: 57, text: "" },
            { time: 58, text: "[Verse 2]" },
            { time: 59, text: "Dicen que el amor es una enfermedad" },
            { time: 63, text: "Me declaro enfermo desde que tú estás" },
            { time: 67, text: "Dicen que los sueños se hacen realidad" },
            { time: 71, text: "No he parado de soñarte nunca más" },
            { time: 75, text: "" },
            { time: 76, text: "[Pre-Chorus]" },
            { time: 77, text: "Y ahora que te vi, te quiero a ti" },
            { time: 81, text: "Y robando corazones, soñaras en mí" },
            { time: 85, text: "" },
            { time: 86, text: "[Chorus]" },
            { time: 87, text: "Yo voy a besarte y voy a cuidarte," },
            { time: 91, text: "Voy a robarte el corazón" },
            { time: 94, text: "Para que creas en mi amor" },
            { time: 97, text: "Yo quiero abrazarte y nunca dejarte" },
            { time: 101, text: "Voy a robarte el corazón y te enamores como yo" },
            { time: 106, text: "" },
            { time: 107, text: "[Montuno]" },
            { time: 108, text: "(Yo voy a besarte, yo quiero abrazarte)" },
            { time: 112, text: "Voy a robarte el corazón y te enamores como yo" },
            { time: 117, text: "(Yo voy a besarte, yo quiero abrazarte)" },
            { time: 121, text: "Y ahora que te vi te quiero a ti," },
            { time: 125, text: "Y robando corazones, soñarás en mí" },
            { time: 129, text: "♪" }
        ],
        memories: []
    },
    {
        id: 7,
        title: "Un siglo o dos",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Un siglo o dos.wav",
        coverImage: "portada/Un siglo o dos.png",
        coverGradient: "from-blue-400 via-purple-500 to-pink-500",
        dedication: "A menudo nos dicen que el amor es un estado de locura transitoria, un error de cálculo que nos hace vulnerables. Pero al encontrarte, reformulé mi hipótesis: quizá la verdadera locura era intentar vivir \"cuerdo\" en un mundo sin color. Tú no llegaste para desordenar mi mente, sino para curar mi corazón. Si amar es de locos, entonces acepto el diagnóstico, porque tú eres la única terapia que funcionó donde la lógica falló.",
        emoji: "💫",
        description: "Capítulo 7: Un siglo o dos",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 5, text: "[Verse 1]" },
            { time: 8, text: "Dicen que amar es de locos" },
            { time: 12, text: "que es arriesgarse a perder la razón" },
            { time: 16, text: "Pero te miro y entiendo" },
            { time: 20, text: "que tú eres la cura de mi corazón." },
            { time: 24, text: "Ya no me importa el pasado" },
            { time: 28, text: "ni las heridas que un día dolieron" },
            { time: 32, text: "Todo valió la pena" },
            { time: 36, text: "si al final tus ojos me vieron." },
            { time: 40, text: "" },
            { time: 41, text: "[Chorus]" },
            { time: 42, text: "Y ahora que estás aquí" },
            { time: 46, text: "haz de mi vida tu casa, tu centro" },
            { time: 50, text: "Que afuera el mundo es ajeno" },
            { time: 54, text: "pero aquí tienes lo que llevo dentro." },
            { time: 58, text: "Quédate un siglo o dos" },
            { time: 62, text: "o quédate solo este instante eterno" },
            { time: 66, text: "Que si es contigo," },
            { time: 68, text: "no existe el frío, no existe el invierno." },
            { time: 72, text: "" },
            { time: 73, text: "[Outro]" },
            { time: 74, text: "Quédate aquí..." },
            { time: 78, text: "donde el tiempo no cuenta." },
            { time: 82, text: "Solo tú y yo." },
            { time: 86, text: "♪" }
        ],
        memories: []
    },
    {
        id: 8,
        title: "No solo palabras",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/No solo palabras.mp3",
        coverImage: "portada/No solo palabras.png",
        coverGradient: "from-rose-400 via-pink-500 to-red-500",
        dedication: "Vivimos en tiempos donde las palabras abundan y a veces pierden su peso, donde decir \"te quiero\" se ha vuelto más fácil que demostrarlo. Y es que, a menudo, caemos en el error de pensar que el amor es un sustantivo, algo que se tiene, cuando en realidad es un verbo: algo que se hace, que se construye. Por eso, hoy no vengo aquí a prometerte futuros inciertos ni a llenar el silencio con frases bonitas que se las podría llevar el viento. Hoy vengo a demostrar. He entendido que el cariño real no vive en la intención, sino en la ejecución. Quiero que escuches esta canción no como una simple melodía, sino como una estructura sólida. Imagina que cada verso que escribí es un paso firme hacia ti, y que cada coro es un refugio, una forma tangible de cuidarte. Que esta letra sea el recordatorio constante de que lo que siento por ti no es abstracto; tiene forma, tiene peso y se ve en los hechos. Porque al final del día, lo único que realmente nos pertenece es lo que entregamos a través de nuestras acciones.",
        emoji: "🔥",
        description: "Capítulo 8: No solo palabras",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 2, text: "[Verso 1]" },
            { time: 6, text: "Pasan las horas, pasan los días" },
            { time: 10, text: "y yo sigo aquí," },
            { time: 14, text: "repasando el guion, de lo que te diría" },
            { time: 18, text: "cuando te vuelva a ver" },
            { time: 22, text: "No hay nadie más, entiéndelo bien" },
            { time: 26, text: "eres el faro que guía mi tren" },
            { time: 30, text: "te quiero a ti, no es una ilusión" },
            { time: 34, text: "eres la dueña de mi corazón." },
            { time: 38, text: "[Pre-Coro]" },
            { time: 42, text: "Solo en mi mente te veo venir" },
            { time: 46, text: "y quiero tenerte, muy cerca de mí." },
            { time: 50, text: "Tú y yo viajando hasta el mismo sinfín" },
            { time: 54, text: "sé que conmigo serás muy feliz..." },
            { time: 58, text: "[Coro]" },
            { time: 62, text: "Te quiero, y te lo demostraré" },
            { time: 66, text: "No son palabras, yo accionaré." },
            { time: 70, text: "Te quiero, y te lo demostraré" },
            { time: 74, text: "Mi amor es fuego, yo te cuidaré." },
            { time: 78, text: "[Verso 2]" },
            { time: 82, text: "Ya me cansé de promesas al viento" },
            { time: 86, text: "hoy traigo hechos, traigo sentimientos." },
            { time: 90, text: "No es un discurso, es una verdad" },
            { time: 94, text: "quiero borrarte la soledad." },
            { time: 98, text: "Dame la mano, vamos a volar" },
            { time: 102, text: "que esta salsa, invita a soñar." },
            { time: 106, text: "[Pre-Coro]" },
            { time: 110, text: "Solo en mi mente te veo venir" },
            { time: 114, text: "y quiero tenerte, muy cerca de mí." },
            { time: 118, text: "Tú y yo viajando hasta el mismo sinfín" },
            { time: 122, text: "sé que conmigo serás muy feliz..." },
            { time: 126, text: "[Coro]" },
            { time: 130, text: "Te quiero, y te lo demostraré" },
            { time: 134, text: "No son palabras, yo accionaré." },
            { time: 138, text: "Te quiero, y te lo demostraré" },
            { time: 142, text: "Mi amor es fuego, yo te cuidaré." },
            { time: 146, text: "[Montuno]" },
            { time: 150, text: "Te quiero y te lo demostraré, con hechos yo te amaré." },
            { time: 154, text: "No me basta con decirlo, mi lady, hoy te bajo las estrellas y las pongo a tus pies." },
            { time: 158, text: "Te quiero y te lo demostraré, con hechos yo te amaré." },
            { time: 162, text: "Pasan las horas y sigo pensando, que tú eres la reina que estoy esperando." },
            { time: 166, text: "Te quiero y te lo demostraré, con hechos yo te amaré." },
            { time: 170, text: "¡Acción, acción! Eso es lo que pides y eso te doy yo." },
            { time: 174, text: "[Outro]" },
            { time: 178, text: "Te quiero y te lo demostraré" },
            { time: 182, text: "Y te lo demostraré..." },
            { time: 186, text: "No solo palabras..." },
            { time: 190, text: "Te lo demostraré..." },
            { time: 194, text: "♪" }
        ],
        memories: []
    },
    {
        id: 9,
        title: "Mi dulce refugio",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Mi dulce refugio.mp3",
        coverImage: "portada/Mi dulce refugio.png",
        coverGradient: "from-rose-300 via-pink-400 to-fuchsia-500",
        dedication: "Fíjate qué curioso es esto... A menudo nos han vendido la idea de que la realidad es únicamente aquello que podemos tocar, aquello que ocupa un espacio físico. Nos dicen que si no está aquí, \"en carne y hueso\", entonces no cuenta, o es una fantasía. Pero escucha bien lo que dice esta canción: \"Soñarte... es la única forma que tengo de verte... Y aunque digan que pierdo mi tiempo...\" Y ahí es donde yo me detengo a pensar: ¿Realmente es perder el tiempo? Porque, piénsalo... si al cerrar los ojos, la emoción que sientes es tan genuina, tan fuerte y tan real que te hace sonreír o te da paz... ¿quién tiene la autoridad para decir que eso no es \"realidad\"? La letra dice: \"Yo sigo aquí, deseando ser el que te hace feliz\". Y creo que esa es la manifestación más pura del amor incondicional. El amor que no pide, que no exige presencia inmediata, sino que se conforma con la posibilidad de dar, aunque sea en el plano de los sueños. Crear un espacio onírico, un refugio mental solo para encontrarse con alguien, no es un acto de locura. Es un acto de resistencia. Es la forma en que el alma se rebela contra las limitaciones del mundo físico y dice: \"No me importa la distancia, ni las circunstancias. Mi vínculo contigo es tan fuerte que he construido un universo entero en mi mente... solo para que tú y yo podamos existir\". Así que no... no estás perdiendo el tiempo. Estás invirtiendo en lo único que trasciende al tiempo y al espacio: el sentimiento. Porque al final del día, si soñarte es la única forma de verte, entonces dormir se convierte en el acto más valiente de despertar al amor. Y eso... eso es lo que le da sentido a todo.",
        emoji: "🌙",
        description: "Capítulo 9: Mi dulce refugio",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 2, text: "[Verso 1]" },
            { time: 6, text: "Cae la noche y el mundo se apaga despacio" },
            { time: 10, text: "Y yo cuento los minutos en este espacio" },
            { time: 14, text: "No busco dormir por cansancio, te confieso" },
            { time: 18, text: "Busco el instante, el atajo y el acceso." },
            { time: 22, text: "A ese rincón donde la distancia no existe" },
            { time: 26, text: "Donde recupero la sonrisa que me diste" },
            { time: 30, text: "Cierro los ojos, no para descansar" },
            { time: 34, text: "Sino para viajar a donde tú estás." },
            { time: 38, text: "[Pre-Coro]" },
            { time: 42, text: "Porque mi realidad se vuelve arte" },
            { time: 46, text: "Cuando comienzo a... soñarte..." },
            { time: 50, text: "Es la única forma que tengo" },
            { time: 54, text: "Yo de verte..." },
            { time: 58, text: "Y aunque digan que pierdo mi tiempo" },
            { time: 62, text: "[Coro]" },
            { time: 66, text: "Yo sigo aquí" },
            { time: 70, text: "Pensando en ti" },
            { time: 74, text: "Deseando ser el que te hace feliz" },
            { time: 78, text: "Yo sigo aquí" },
            { time: 82, text: "Pensando en ti..." },
            { time: 86, text: "Y deseando siempre estar..." },
            { time: 90, text: "Para ti..." },
            { time: 94, text: "Para cuidar tus pasos, aunque sea en mi mente" },
            { time: 98, text: "Para amarte en secreto, locamente" },
            { time: 102, text: "Para ser tu paisaje, tu sol y tu mar" },
            { time: 106, text: "Hasta que el día me vuelva a despertar." },
            { time: 110, text: "[Verso 2]" },
            { time: 114, text: "En mis sueños no hay horas, ni trenes que parten" },
            { time: 118, text: "Solo tus manos que con las mías comparten" },
            { time: 122, text: "Un paseo eterno bajo un cielo distinto" },
            { time: 126, text: "Donde nuestro amor es el único laberinto." },
            { time: 130, text: "Ahí puedo decirte todo lo que callo" },
            { time: 134, text: "Ahí eres mi reina y yo soy tu vasallo" },
            { time: 138, text: "Y si la vida afuera me pide olvidar" },
            { time: 142, text: "Yo vuelvo a mi almohada para recordar." },
            { time: 146, text: "[Pre-Coro]" },
            { time: 150, text: "Que la magia empieza al... soñarte..." },
            { time: 154, text: "Es la única forma que tengo" },
            { time: 158, text: "Yo de verte..." },
            { time: 162, text: "Y aunque digan que pierdo mi tiempo" },
            { time: 166, text: "[Coro]" },
            { time: 170, text: "Yo sigo aquí" },
            { time: 174, text: "Pensando en ti" },
            { time: 178, text: "Deseando ser el que te hace feliz" },
            { time: 182, text: "Yo sigo aquí" },
            { time: 186, text: "Pensando en ti..." },
            { time: 190, text: "Y deseando siempre estar..." },
            { time: 194, text: "Para ti..." },
            { time: 198, text: "[Puente]" },
            { time: 202, text: "Tal vez algún día el sueño sea cierto" },
            { time: 206, text: "Y despierte contigo a cielo abierto" },
            { time: 210, text: "Pero mientras el destino decide llegar" },
            { time: 214, text: "Te prometo, mi vida, que te voy a esperar." },
            { time: 218, text: "[Outro]" },
            { time: 222, text: "Aunque sea en sueños..." },
            { time: 226, text: "Yo sigo aquí." },
            { time: 230, text: "Pensando en ti." },
            { time: 234, text: "Solo para ti..." },
            { time: 238, text: "♪" }
        ],
        memories: []
    },
    {
        id: 10,
        title: "El Pionero de tu Amor (2026)",
        artist: "Dedicatoria Especial",
        type: "Aniversario",
        isNew: true,
        audioUrl: "audio/El pionero de tu amor (2026).mp3",
        coverImage: "portada/El pionero de tu amor (2026).png",
        coverGradient: "from-amber-400 via-orange-500 to-rose-500",
        dedication: "Hay algo curioso del tiempo... Uno cree que sirve para responder preguntas, pero a veces hace exactamente lo contrario, las vuelve innecesarias.\n\nHace un año todavía intentaba entender lo que me pasaba contigo. Buscaba definiciones, explicaciones, alguna teoría que justificara por qué mi mundo parecía cambiar cada vez que aparecías. Pensaba que, si lograba ponerle un nombre a todo aquello, entonces podría sentirme tranquilo (Que equivocado estaba).\n\nPorque hay sentimientos que no nacieron para ser entendidos, nacieron para ser vividos.\n\nHoy ya no necesito preguntarme si esto es amor o si es una ilusión. No porque tenga todas las respuestas, sino porque entendí que hay verdades que el corazón reconoce mucho antes de que la mente las acepte.\n\nY sigo sintiéndome un pionero.\n\nNo porque sea la primera vez que alguien ama a otra persona, sino porque nadie, en toda la historia, ha sentido exactamente esto que yo siento por ti. Este territorio emocional existe una sola vez, porque existe entre una sola versión de ti y una sola versión de mí.\n\nContigo descubrí que amar no siempre significa perder el control. A veces significa encontrar un lugar donde el alma descansa. Descubrí que las mariposas no desaparecen cuando el sentimiento madura; simplemente dejan de volar desordenadas y empiezan a construir un hogar.\n\nTú me enseñaste que la belleza no está en ser perfecta, sino en ser auténtica. Incluso esas partes de ti que a veces escondes, las que llamas defectos, fueron las mismas que me hicieron quedarme. Porque nunca me enamoré de una versión idealizada de ti. Me enamoré de la mujer real, de la que ríe sin darse cuenta, de la que a veces duda de sí misma, de la que sigue siendo increíble incluso en los días en que ella no logra verlo.\n\nY si algo cambió entre aquella canción y esta, no fue lo que siento por ti. Cambió la manera de comprenderlo.\n\nAntes pensaba que tú eras el destino del viaje.\n\nHoy entiendo que también fuiste el camino.\n\nGracias por enseñarme que el amor más bonito no es el que responde todas las preguntas, sino el que hace que dejen de importar.\n\nPorque sigo siendo un pionero, solo que ahora ya no estoy buscando un mapa.\n\nAhora sé que el lugar más extraordinario que podía descubrir... siempre fuiste tú.",
        emoji: "📍",
        description: "Edición Aniversario · 2026",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 2, text: "[Verso 1]" },
            { time: 6, text: "Me despierto y la duda viene a visitarme" },
            { time: 10, text: "camina por mi cuarto, intenta interrogarme." },
            { time: 14, text: "Me pregunta por qué tiemblo si escucho tu voz," },
            { time: 18, text: "si esto es para siempre o es cosa de dos." },
            { time: 22, text: "Miro al techo y busco una explicación," },
            { time: 26, text: "no sé si esto es amor" },
            { time: 30, text: "o si solo es una ilusión." },
            { time: 34, text: "[Pre-Coro]" },
            { time: 38, text: "Pero entonces llegas tú," },
            { time: 42, text: "y la lógica se apaga, se va la luz." },
            { time: 46, text: "Ya no importan las preguntas, ni el miedo," },
            { time: 50, text: "solo importa que estás aquí, y no me quedo quieto." },
            { time: 54, text: "[Coro]" },
            { time: 58, text: "Porque pasa que soy pionero" },
            { time: 62, text: "en descubrir mapas que no conocía," },
            { time: 66, text: "en sentir todo lo que siento" },
            { time: 70, text: "cada vez que tú me miras." },
            { time: 74, text: "Y es lo que pasa, cuando te veo" },
            { time: 78, text: "la gravedad se invierte, alzo el vuelo," },
            { time: 82, text: "y siento muchas mariposas" },
            { time: 86, text: "bailando por todo mi cuerpo," },
            { time: 90, text: "haciendo fiesta en mi pecho." },
            { time: 94, text: "[Verso 2]" },
            { time: 98, text: "Nunca antes nadie me hizo sentir así," },
            { time: 102, text: "como si el mundo empezara justo en ti." },
            { time: 106, text: "Antes de tu risa yo era un turista más," },
            { time: 110, text: "caminando sin rumbo, mirando hacia atrás." },
            { time: 114, text: "Pero ahora tengo una misión urgente:" },
            { time: 118, text: "quererte despacio, quererte fuerte." },
            { time: 122, text: "[Coro]" },
            { time: 126, text: "Porque pasa que soy pionero" },
            { time: 130, text: "en descubrir mapas que no conocía," },
            { time: 134, text: "en sentir todo lo que siento" },
            { time: 138, text: "cada vez que tú me miras." },
            { time: 142, text: "Y es lo que pasa, cuando te veo" },
            { time: 146, text: "la gravedad se invierte, alzo el vuelo," },
            { time: 150, text: "y siento muchas mariposas" },
            { time: 154, text: "bailando por todo mi cuerpo." },
            { time: 158, text: "[Puente]" },
            { time: 162, text: "Y si es una ilusión, que no me despierten," },
            { time: 166, text: "que este sueño es lo mejor que he tenido." },
            { time: 170, text: "Pero si es amor..." },
            { time: 174, text: "entonces soy el hombre más afortunado de haberte conocido." },
            { time: 178, text: "[Outro]" },
            { time: 182, text: "Sí... soy un pionero." },
            { time: 186, text: "Descubriendo el amor..." },
            { time: 190, text: "cuando te veo" },
            { time: 194, text: "Siento mariposas..." },
            { time: 198, text: "solo mariposas..." },
            { time: 202, text: "♪" }
        ],
        memories: []
    },
    {
        id: 11,
        title: "Antes de que pase (Acústico)",
        artist: "Dedicatoria Especial",
        type: "Original",
        isNew: true,
        audioUrl: "audio/Antes de que pase (Acústico).mp3",
        coverImage: "portada/Antes de que pase (Acústico).png",
        coverGradient: "from-amber-300 via-orange-400 to-rose-400",
        dedication: "Todavía no sé cuáles serán nuestros lugares favoritos, qué canciones terminaremos haciendo nuestras, qué viajes recordaremos con una sonrisa o qué pequeñas costumbres inventaremos sin darnos cuenta.\n\nY, sinceramente, no quiero saberlo todavía.\n\nPorque una de las cosas más bonitas de encontrarte es descubrir que todavía nos queda muchísimo por vivir.\n\nNo sé qué habrá a la vuelta de cada día, pero sí sé algo: me hace ilusión descubrirlo contigo.\n\nQue nos queden primeras veces, planes improvisados, historias que todavía no existen y recuerdos que algún día miraremos desde lejos pensando en todo lo que nos faltaba por conocer.\n\nDe todo lo que la vida todavía puede escribir, qué bonito que una parte de eso pueda ser contigo.",
        emoji: "⏳",
        description: "Capítulo 11: Antes de que pase (Acústico)",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 4, text: "[Verso 1]" },
            { time: 8, text: "Aún no hay fotos en la nevera," },
            { time: 12, text: "ni dos juegos de llaves al entrar." },
            { time: 16, text: "No sé qué canción pondrás en la sala," },
            { time: 20, text: "cuando el tiempo nos deje de importar." },
            { time: 24, text: "Pero me encanta cerrar los ojos" },
            { time: 28, text: "y ver todo lo que nos falta hacer." },
            { time: 32, text: "Una escapada sin motivos," },
            { time: 36, text: "y un domingo al amanecer." },
            { time: 40, text: "[Pre-Coro]" },
            { time: 44, text: "Porque qué bonito es no saber (no saber)" },
            { time: 48, text: "todo lo que el destino nos dará." },
            { time: 52, text: "Si lo mejor de nuestra historia" },
            { time: 56, text: "a la vuelta de la esquina está..." },
            { time: 60, text: "[Coro]" },
            { time: 64, text: "¡Quiero vivirlo contigo, antes de que pase!" },
            { time: 68, text: "Que la vida nos encuentre en cualquier parte." },
            { time: 72, text: "Llenar nuestros días de cosas que recordar," },
            { time: 76, text: "y al mirar atrás, mil razones para regresar." },
            { time: 80, text: "¡Quiero vivirlo contigo, todo lo que viene!" },
            { time: 84, text: "Noches de locura y días que sorprenden." },
            { time: 88, text: "Y si mañana cambia el mundo, que nos encuentre igual:" },
            { time: 92, text: "Tú riendo conmigo..." },
            { time: 96, text: "¡Y yo queriéndote un poco más!" },
            { time: 100, text: "[Post-Coro]" },
            { time: 104, text: "(Un poco más) Oh, oh, oh!" },
            { time: 108, text: "(Un poco más...)" },
            { time: 112, text: "[Verso 2]" },
            { time: 116, text: "Aún no sé qué lado de la cama" },
            { time: 120, text: "es el que siempre vas a elegir." },
            { time: 124, text: "Ni cuál será tu excusa perfecta" },
            { time: 128, text: "para abrazarnos y no salir." },
            { time: 132, text: "Y qué bonito que nos queden" },
            { time: 136, text: "tantas primeras veces por sentir." },
            { time: 140, text: "El rincón al que siempre volvamos," },
            { time: 144, text: "y esa broma que te haga sonreír." },
            { time: 148, text: "[Pre-Coro]" },
            { time: 152, text: "Porque qué bonito tener tanto por descubrir," },
            { time: 156, text: "si lo que me emociona es lo que falta vivir." },
            { time: 160, text: "Abre los ojos..." },
            { time: 164, text: "¡Allá vamos!" },
            { time: 168, text: "[Coro]" },
            { time: 172, text: "¡Quiero vivirlo contigo, antes de que pase!" },
            { time: 176, text: "Que la vida nos encuentre en cualquier parte." },
            { time: 180, text: "Llenar nuestros días de cosas que recordar," },
            { time: 184, text: "y al mirar atrás, mil razones para regresar." },
            { time: 188, text: "¡Quiero vivirlo contigo, todo lo que viene!" },
            { time: 192, text: "Noches de locura y días que sorprenden." },
            { time: 196, text: "Y si mañana cambia el mundo, que nos encuentre igual:" },
            { time: 200, text: "Tú riendo conmigo..." },
            { time: 204, text: "¡Y yo queriéndote un poco más!" },
            { time: 208, text: "[Puente]" },
            { time: 212, text: "Y cuando pasen los años, en nuestra propia casa..." },
            { time: 216, text: "quizá en una noche me mires y digas:" },
            { time: 220, text: "\"¿Te acuerdas de cuando no sabíamos nada?\"" },
            { time: 224, text: "Y yo sonreiré por esta casualidad..." },
            { time: 228, text: "¡Porque nos quedaba una vida por estrenar!" },
            { time: 232, text: "[Último Coro]" },
            { time: 236, text: "¡Quiero vivirlo contigo, antes de que pase!" },
            { time: 240, text: "Que la vida nos encuentre en cualquier parte." },
            { time: 244, text: "Llenar nuestros días de cosas que recordar," },
            { time: 248, text: "y al mirar atrás, mil razones para regresar." },
            { time: 252, text: "¡Quiero vivirlo contigo! (¡Sí, contigo!)" },
            { time: 256, text: "Las noches, los días, todo lo que viene." },
            { time: 260, text: "Y si mañana cambia el mundo, que nos encuentre igual:" },
            { time: 264, text: "Tú riendo conmigo..." },
            { time: 268, text: "¡Y yo queriéndote un poco más!" },
            { time: 272, text: "[Outro]" },
            { time: 276, text: "Todavía nos queda tanto por vivir..." },
            { time: 280, text: "Y qué bonito..." },
            { time: 284, text: "Que sea contigo." },
            { time: 288, text: "♪" }
        ],
        memories: []
    },
    {
        id: 12,
        title: "Quédate",
        artist: "Dedicatoria Especial",
        type: "Original",
        isNew: true,
        audioUrl: "audio/Quédate.mp3",
        coverImage: "portada/Quédate.png",
        coverGradient: "from-orange-300 via-amber-400 to-rose-400",
        dedication: "Quizá no nos dimos cuenta de cuándo empezamos a hacernos un lugar en los días del otro.\n\nNo sé qué nombre tendrá todo esto mañana, ni quiero apresurarlo.\n\nSolo sé que me gusta coincidir contigo, compartir lo pequeño, reírnos de cualquier cosa y descubrir, poco a poco, esta versión de nosotros que antes no conocíamos.\n\nAsí que no quiero pedirte promesas.\n\nPor ahora, solo quiero decirte algo muy sencillo: qué bonito es que estés aquí.\n\nY si tú quieres, quédate un poquito más.",
        emoji: "☕",
        description: "Capítulo 12: Quédate",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 4, text: "[Verso 1]" },
            { time: 8, text: "No sé cuándo te volviste" },
            { time: 12, text: "parte de mis días" },
            { time: 16, text: "Creo que fue poco a poco" },
            { time: 20, text: "sin que yo lo decidiera" },
            { time: 24, text: "Primero fueron tus mensajes" },
            { time: 28, text: "después querer verte un rato" },
            { time: 32, text: "Y ahora cuando algo me pasa" },
            { time: 36, text: "eres la primera a quien llamo" },
            { time: 40, text: "Me sé de memoria" },
            { time: 44, text: "tus historias repetidas" },
            { time: 48, text: "Y todavía me río" },
            { time: 52, text: "aunque ya sé cómo terminan" },
            { time: 56, text: "Supongo que así empieza" },
            { time: 60, text: "eso que llaman querer" },
            { time: 64, text: "Sin darte cuenta un día" },
            { time: 68, text: "ya no quieres estar sin él" },
            { time: 72, text: "[Pre-Coro]" },
            { time: 76, text: "Y no quiero apresurarlo" },
            { time: 80, text: "no quiero ponerle nombre" },
            { time: 84, text: "Solo sé que cuando estás conmigo" },
            { time: 88, text: "todo se siente donde corresponde" },
            { time: 92, text: "[Coro]" },
            { time: 96, text: "Quédate a vivir" },
            { time: 100, text: "un poquito en mis días" },
            { time: 104, text: "Quédate a reír" },
            { time: 108, text: "de todas mis tonterías" },
            { time: 112, text: "Quédate cuando llueva" },
            { time: 116, text: "cuando no tenga nada que decir" },
            { time: 120, text: "Quédate porque contigo" },
            { time: 124, text: "me gusta más ser yo así" },
            { time: 128, text: "Y si mañana cambia todo" },
            { time: 132, text: "lo hablamos después" },
            { time: 136, text: "Hoy solo quiero que te quedes" },
            { time: 140, text: "Quédate" },
            { time: 144, text: "[Verso 2]" },
            { time: 148, text: "A veces llegas cansada" },
            { time: 152, text: "y no quieres hablar de nada" },
            { time: 156, text: "Entonces pongo una película" },
            { time: 160, text: "que ninguno termina" },
            { time: 164, text: "Y terminamos conversando" },
            { time: 168, text: "de cualquier cosa en la sala" },
            { time: 172, text: "Hasta que miramos la hora" },
            { time: 176, text: "y ya casi es mañana" },
            { time: 180, text: "No tenemos grandes planes" },
            { time: 184, text: "ni sabemos qué vendrá" },
            { time: 188, text: "Pero me gusta esta manera" },
            { time: 192, text: "de aprendernos sin preguntar" },
            { time: 196, text: "Y quizá eso es lo bonito" },
            { time: 200, text: "que no tengo que inventar" },
            { time: 204, text: "Una versión mejor de mí" },
            { time: 208, text: "cuando tú me ves llegar" },
            { time: 212, text: "[Pre-Coro]" },
            { time: 216, text: "Y no quiero apresurarlo" },
            { time: 220, text: "no quiero ponerle nombre" },
            { time: 224, text: "Solo sé que cuando estás conmigo" },
            { time: 228, text: "todo se siente donde corresponde" },
            { time: 232, text: "[Coro]" },
            { time: 236, text: "Quédate a vivir" },
            { time: 240, text: "un poquito en mis días" },
            { time: 244, text: "Quédate a reír" },
            { time: 248, text: "de todas mis tonterías" },
            { time: 252, text: "Quédate cuando llueva" },
            { time: 256, text: "cuando no tenga nada que decir" },
            { time: 260, text: "Quédate porque contigo" },
            { time: 264, text: "me gusta más ser yo así" },
            { time: 268, text: "Y si mañana cambia todo" },
            { time: 272, text: "lo hablamos después" },
            { time: 276, text: "Hoy solo quiero que te quedes" },
            { time: 280, text: "Quédate" },
            { time: 284, text: "[Puente]" },
            { time: 288, text: "Y si algún día" },
            { time: 292, text: "nos toca estar lejos" },
            { time: 296, text: "No quiero promesas" },
            { time: 300, text: "que no podamos cumplir" },
            { time: 304, text: "Solo dime que cuando vuelvas" },
            { time: 308, text: "vas a buscarme" },
            { time: 312, text: "Porque yo voy a estar aquí" },
            { time: 316, text: "Con la misma canción" },
            { time: 320, text: "que nunca terminamos" },
            { time: 324, text: "Con aquel café" },
            { time: 328, text: "que siempre dejamos a medias" },
            { time: 332, text: "Y todas esas cosas pequeñas" },
            { time: 336, text: "que nadie más entendería" },
            { time: 340, text: "[Último Coro]" },
            { time: 344, text: "Quédate a vivir" },
            { time: 348, text: "un poquito en mis días" },
            { time: 352, text: "Quédate a reír" },
            { time: 356, text: "de todas mis tonterías" },
            { time: 360, text: "Quédate cuando llueva" },
            { time: 364, text: "cuando no tenga nada que decir" },
            { time: 368, text: "Quédate porque contigo" },
            { time: 372, text: "me gusta más ser yo así" },
            { time: 376, text: "Y si mañana cambia todo" },
            { time: 380, text: "lo hablamos después" },
            { time: 384, text: "Si la vida nos mueve el suelo" },
            { time: 388, text: "lo volvemos a hacer" },
            { time: 392, text: "Pero hoy..." },
            { time: 396, text: "hoy solo quiero que te quedes" },
            { time: 400, text: "Quédate" },
            { time: 404, text: "[Outro]" },
            { time: 408, text: "No tienes que prometerme nada" },
            { time: 412, text: "Solo quédate" },
            { time: 416, text: "Un poquito más" },
            { time: 420, text: "♪" }
        ],
        memories: []
    },
    {
        id: 13,
        title: "Quédate (Acústico)",
        artist: "Dedicatoria Especial",
        type: "Original",
        isNew: true,
        audioUrl: "audio/Quédate (Acústico).mp3",
        coverImage: "portada/Quédate.png",
        coverGradient: "from-orange-300 via-amber-400 to-rose-400",
        dedication: "Quizá no nos dimos cuenta de cuándo empezamos a hacernos un lugar en los días del otro.\n\nNo sé qué nombre tendrá todo esto mañana, ni quiero apresurarlo.\n\nSolo sé que me gusta coincidir contigo, compartir lo pequeño, reírnos de cualquier cosa y descubrir, poco a poco, esta versión de nosotros que antes no conocíamos.\n\nAsí que no quiero pedirte promesas.\n\nPor ahora, solo quiero decirte algo muy sencillo: qué bonito es que estés aquí.\n\nY si tú quieres, quédate un poquito más.",
        emoji: "☕",
        description: "Capítulo 13: Quédate (Acústico)",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 4, text: "[Verso 1]" },
            { time: 8, text: "No sé cuándo te volviste" },
            { time: 12, text: "parte de mis días" },
            { time: 16, text: "Creo que fue poco a poco" },
            { time: 20, text: "sin que yo lo decidiera" },
            { time: 24, text: "Primero fueron tus mensajes" },
            { time: 28, text: "después querer verte un rato" },
            { time: 32, text: "Y ahora cuando algo me pasa" },
            { time: 36, text: "eres la primera a quien llamo" },
            { time: 40, text: "Me sé de memoria" },
            { time: 44, text: "tus historias repetidas" },
            { time: 48, text: "Y todavía me río" },
            { time: 52, text: "aunque ya sé cómo terminan" },
            { time: 56, text: "Supongo que así empieza" },
            { time: 60, text: "eso que llaman querer" },
            { time: 64, text: "Sin darte cuenta un día" },
            { time: 68, text: "ya no quieres estar sin él" },
            { time: 72, text: "[Pre-Coro]" },
            { time: 76, text: "Y no quiero apresurarlo" },
            { time: 80, text: "no quiero ponerle nombre" },
            { time: 84, text: "Solo sé que cuando estás conmigo" },
            { time: 88, text: "todo se siente donde corresponde" },
            { time: 92, text: "[Coro]" },
            { time: 96, text: "Quédate a vivir" },
            { time: 100, text: "un poquito en mis días" },
            { time: 104, text: "Quédate a reír" },
            { time: 108, text: "de todas mis tonterías" },
            { time: 112, text: "Quédate cuando llueva" },
            { time: 116, text: "cuando no tenga nada que decir" },
            { time: 120, text: "Quédate porque contigo" },
            { time: 124, text: "me gusta más ser yo así" },
            { time: 128, text: "Y si mañana cambia todo" },
            { time: 132, text: "lo hablamos después" },
            { time: 136, text: "Hoy solo quiero que te quedes" },
            { time: 140, text: "Quédate" },
            { time: 144, text: "[Verso 2]" },
            { time: 148, text: "A veces llegas cansada" },
            { time: 152, text: "y no quieres hablar de nada" },
            { time: 156, text: "Entonces pongo una película" },
            { time: 160, text: "que ninguno termina" },
            { time: 164, text: "Y terminamos conversando" },
            { time: 168, text: "de cualquier cosa en la sala" },
            { time: 172, text: "Hasta que miramos la hora" },
            { time: 176, text: "y ya casi es mañana" },
            { time: 180, text: "No tenemos grandes planes" },
            { time: 184, text: "ni sabemos qué vendrá" },
            { time: 188, text: "Pero me gusta esta manera" },
            { time: 192, text: "de aprendernos sin preguntar" },
            { time: 196, text: "Y quizá eso es lo bonito" },
            { time: 200, text: "que no tengo que inventar" },
            { time: 204, text: "Una versión mejor de mí" },
            { time: 208, text: "cuando tú me ves llegar" },
            { time: 212, text: "[Pre-Coro]" },
            { time: 216, text: "Y no quiero apresurarlo" },
            { time: 220, text: "no quiero ponerle nombre" },
            { time: 224, text: "Solo sé que cuando estás conmigo" },
            { time: 228, text: "todo se siente donde corresponde" },
            { time: 232, text: "[Coro]" },
            { time: 236, text: "Quédate a vivir" },
            { time: 240, text: "un poquito en mis días" },
            { time: 244, text: "Quédate a reír" },
            { time: 248, text: "de todas mis tonterías" },
            { time: 252, text: "Quédate cuando llueva" },
            { time: 256, text: "cuando no tenga nada que decir" },
            { time: 260, text: "Quédate porque contigo" },
            { time: 264, text: "me gusta más ser yo así" },
            { time: 268, text: "Y si mañana cambia todo" },
            { time: 272, text: "lo hablamos después" },
            { time: 276, text: "Hoy solo quiero que te quedes" },
            { time: 280, text: "Quédate" },
            { time: 284, text: "[Puente]" },
            { time: 288, text: "Y si algún día" },
            { time: 292, text: "nos toca estar lejos" },
            { time: 296, text: "No quiero promesas" },
            { time: 300, text: "que no podamos cumplir" },
            { time: 304, text: "Solo dime que cuando vuelvas" },
            { time: 308, text: "vas a buscarme" },
            { time: 312, text: "Porque yo voy a estar aquí" },
            { time: 316, text: "Con la misma canción" },
            { time: 320, text: "que nunca terminamos" },
            { time: 324, text: "Con aquel café" },
            { time: 328, text: "que siempre dejamos a medias" },
            { time: 332, text: "Y todas esas cosas pequeñas" },
            { time: 336, text: "que nadie más entendería" },
            { time: 340, text: "[Último Coro]" },
            { time: 344, text: "Quédate a vivir" },
            { time: 348, text: "un poquito en mis días" },
            { time: 352, text: "Quédate a reír" },
            { time: 356, text: "de todas mis tonterías" },
            { time: 360, text: "Quédate cuando llueva" },
            { time: 364, text: "cuando no tenga nada que decir" },
            { time: 368, text: "Quédate porque contigo" },
            { time: 372, text: "me gusta más ser yo así" },
            { time: 376, text: "Y si mañana cambia todo" },
            { time: 380, text: "lo hablamos después" },
            { time: 384, text: "Si la vida nos mueve el suelo" },
            { time: 388, text: "lo volvemos a hacer" },
            { time: 392, text: "Pero hoy..." },
            { time: 396, text: "hoy solo quiero que te quedes" },
            { time: 400, text: "Quédate" },
            { time: 404, text: "[Outro]" },
            { time: 408, text: "No tienes que prometerme nada" },
            { time: 412, text: "Solo quédate" },
            { time: 416, text: "Un poquito más" },
            { time: 420, text: "♪" }
        ],
        memories: []
    }
];
