// Base de datos de canciones
const tracks = [
    {
        id: 1,
        title: "Si eres tú",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Si eres tú.wav",
        coverImage: "portada/Si Eres Tú.png",
        coverGradient: "from-pink-500 via-rose-500 to-red-500",
        dedication: "Vivimos en un universo que tiende naturalmente al caos, a la entropía, y entre tantas variables infinitas, la probabilidad de cruzarnos era casi nula. Sin embargo, sucediste. Si antes mi realidad era una secuencia monótona de grises, tu llegada funcionó como el prisma que necesitaba para entender la luz. Esta canción es la prueba de que, a veces, la vida no necesita ser perfecta para tener sentido; solo necesita a la persona correcta para tener color.",
        emoji: "💖",
        description: "Capítulo 1: Si eres tú",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 15, text: "[Verse 1]" },
            { time: 19, text: "Qué pensará tu papá" },
            { time: 23, text: "si se entera que su hija consentida se robó mis latidos" },
            { time: 29, text: "Y contarle a tu mamá" },
            { time: 33, text: "que ya tienes quien te sirva de refugio y te sirva de abrigo" },
            { time: 39, text: "Tienes esa forma de ser" },
            { time: 43, text: "que me gana cada vez que te acercas, cada que te miro" },
            { time: 49, text: "Tanto tiempo te soñé" },
            { time: 53, text: "y hoy por fin te tengo..." },
            { time: 57, text: "" },
            { time: 58, text: "[Chorus]" },
            { time: 59, text: "No podría dejarte..." },
            { time: 63, text: "si solo con mirarte..." },
            { time: 67, text: "mi gris deja de ser gris" },
            { time: 71, text: "y empieza a tener sentido" },
            { time: 75, text: "no podría dejarte..." },
            { time: 79, text: "¿cómo no enamorarme?" },
            { time: 83, text: "si eres tú" },
            { time: 86, text: "Si eres tú" },
            { time: 88, text: "si eres tú" },
            { time: 90, text: "Si eres tú" },
            { time: 92, text: "si eres tú quien le dió color a mi vida..." },
            { time: 97, text: "" },
            { time: 98, text: "[Verse 2]" },
            { time: 99, text: "Se lo digo a tu papá" },
            { time: 103, text: "que me diste la alegría que le falta a mis días vacíos" },
            { time: 109, text: "Y le explico a tu mamá" },
            { time: 113, text: "que sus rezos funcionaron pa' que cruces tu camino al mío" },
            { time: 119, text: "No hace falta nada más" },
            { time: 123, text: "porque todo lo que quiero lo tengo justo aquí contigo" },
            { time: 129, text: "Tanto tiempo lo soñé" },
            { time: 133, text: "y hoy aquí te tengo" },
            { time: 137, text: "" },
            { time: 138, text: "[Chorus]" },
            { time: 139, text: "No podría dejarte..." },
            { time: 143, text: "si solo con mirarte..." },
            { time: 147, text: "mi gris deja de ser gris" },
            { time: 151, text: "y empieza a tener sentido" },
            { time: 155, text: "no podría dejarte..." },
            { time: 159, text: "cómo no enamorarme?" },
            { time: 163, text: "si eres tú" },
            { time: 166, text: "Si eres tú" },
            { time: 168, text: "si eres tú" },
            { time: 170, text: "Si eres tú" },
            { time: 172, text: "si eres tú quien le dió color a mi vida..." },
            { time: 177, text: "" },
            { time: 178, text: "[Outro]" },
            { time: 179, text: "Si eres tú..." },
            { time: 183, text: "quien le da sentido" },
            { time: 187, text: "a mis días." },
            { time: 191, text: "♪" }
        ]
    },
    {
        id: 2,
        title: "Mi cora... y más",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Mi cora... y más.wav",
        coverImage: "portada/Mi cora... y más.png",
        coverGradient: "from-orange-400 via-red-500 to-pink-500",
        dedication: "Vivimos en un universo de variables infinitas, donde la mayoría de las melodías son ruido de fondo, intercambiables y efímeras. Pero existen ciertas frecuencias que nacen con un propósito singular, diseñadas para resonar con una sola alma en toda la existencia. Esta canción no te la dedico; esta canción te pertenece por derecho ontológico. Lleva tu huella dactilar metafísica codificada en su ritmo y en el juego de palabras que solo tu nombre puede completar. Es intransferible, porque para que alguien más pudiera reclamarla, tendría que suceder lo imposible: tendrían que ser tú.",
        emoji: "💝",
        description: "Capítulo 2: Mi cora... y más",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 6, text: "[Verse 1]" },
            { time: 8, text: "Perdona si vengo a buscarte así" },
            { time: 12, text: "No aguantaba más sin saber de ti" },
            { time: 16, text: "No traigo castillos ni falsa ilusión" },
            { time: 20, text: "Solo te ofrezco mi fiel corazón" },
            { time: 24, text: "" },
            { time: 24.5, text: "[Pre-Chorus]" },
            { time: 25, text: "Que sepa tu padre y también mamá" },
            { time: 29, text: "Que este loco te quiere con sinceridad" },
            { time: 33, text: "No busco aventuras vengo por tu amor" },
            { time: 37, text: "A cuidar por siempre de tu corazón" },
            { time: 41, text: "" },
            { time: 41.5, text: "[Chorus]" },
            { time: 42, text: "Porque tienes mi Cora" },
            { time: 45, text: "Y más que soñar" },
            { time: 47, text: "Tú tienes la magia de hacerme volar" },
            { time: 51, text: "Eres mi Cora" },
            { time: 53, text: "Y más mi verdad" },
            { time: 55, text: "Si me das un sí me voy a quedar" },
            { time: 59, text: "" },
            { time: 59.5, text: "[Verse 2]" },
            { time: 60, text: "Dicen que estamos muy chicos los dos" },
            { time: 64, text: "Pero esto es grande lo juro por Dios" },
            { time: 68, text: "El tiempo dirá que tengo razón" },
            { time: 72, text: "Que tú eres la dueña de mi devoción" },
            { time: 76, text: "" },
            { time: 76.5, text: "[Chorus]" },
            { time: 77, text: "Porque tienes mi Cora" },
            { time: 80, text: "Y más que soñar" },
            { time: 82, text: "Tú tienes la magia de hacerme volar" },
            { time: 86, text: "Eres mi Cora" },
            { time: 88, text: "Y más mi verdad" },
            { time: 90, text: "Si me das un sí me voy a quedar" },
            { time: 94, text: "" },
            { time: 94.5, text: "[Montuno]" },
            { time: 95, text: "Tú tienes mi Cora, y más... mucho más" },
            { time: 100, text: "Oye mi niña bonita, no te vayas jamás" },
            { time: 105, text: "Tú tienes mi Cora, y más... mucho más" },
            { time: 110, text: "Es que mi Cora... imagina todo lo que me das" },
            { time: 115, text: "Tú tienes mi Cora, y más... mucho más" },
            { time: 120, text: "Te vengo a robar, te vengo a adorar..." },
            { time: 124, text: "¡con respeto te voy a cuidar!" },
            { time: 128, text: "♪" }
        ],
        memories: []
    },
    {
        id: 3,
        title: "Fuera de Guion",
        artist: "Dedicatoria Especial",
        type: "Original",
        audioUrl: "audio/Fuera de Guion.wav",
        coverImage: "portada/Fuera de Guion.png",
        coverGradient: "from-amber-400 via-orange-500 to-red-500",
        dedication: "Nos pasamos la vida obsesionados con ser los autores de nuestro propio destino, creyendo que tener el control del guion es la única forma de evitar el caos. Sin embargo, las mejores historias no son las que se planean milimétricamente, sino las que se rompen por un giro inesperado. Tú fuiste ese plot twist en mi narrativa; la improvisación que no vi venir pero que terminó salvando la trama. Gracias por enseñarme que la vida no se trata de seguir un libreto perfecto, sino de encontrar a alguien con quien valga la pena salirse del guion.",
        emoji: "📖",
        description: "Capítulo 3: Fuera de Guion",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 5, text: "[Verse 1]" },
            { time: 8, text: "Yo era el rey del drama, el de la tinta gris" },
            { time: 12, text: "Escribiendo tragedias donde no era feliz." },
            { time: 16, text: "Tenía mi libreta llena de tachones" },
            { time: 20, text: "Buscando culpables, buscando razones." },
            { time: 24, text: "Mi vida era un libro de esos aburridos" },
            { time: 28, text: "De los que se quedan a medias, dormidos." },
            { time: 32, text: "" },
            { time: 34, text: "[Pre-Chorus]" },
            { time: 36, text: "Pero llegaste tú con ese resaltador" },
            { time: 40, text: "A cambiarme la letra, a cambiarme el color." },
            { time: 44, text: "No pediste permiso para editar" },
            { time: 48, text: "Lo que yo juraba que no iba a cambiar." },
            { time: 52, text: "Y le diste la vuelta a la página diez..." },
            { time: 56, text: "" },
            { time: 58, text: "[Chorus]" },
            { time: 60, text: "¡Y ahora no sigo el guion!" },
            { time: 64, text: "Me hiciste un plot twist en el corazón." },
            { time: 68, text: "Yo iba para el sur y tú me llevaste al norte" },
            { time: 72, text: "Rompiste mis esquemas, rompiste el soporte." },
            { time: 76, text: "No sé qué capítulo es, ni cómo termina" },
            { time: 80, text: "Pero es mi favorito si tú eres la heroína." },
            { time: 84, text: "" },
            { time: 86, text: "[Verse 2]" },
            { time: 88, text: "Mis amigos dicen: \"¿Qué le pasó al poeta?" },
            { time: 92, text: "Que ahora anda riendo, que rompió la careta\"." },
            { time: 96, text: "Es que contigo el drama ya no me combina" },
            { time: 100, text: "Tú eres comedia romántica y adrenalina." },
            { time: 104, text: "Borraste al villano, quitaste el dolor" },
            { time: 108, text: "Y ahora la trama me suena mejor." },
            { time: 112, text: "" },
            { time: 114, text: "[Chorus]" },
            { time: 116, text: "¡Y ahora no sigo el guion!" },
            { time: 120, text: "Me hiciste un plot twist en el corazón." },
            { time: 124, text: "Yo iba para el sur y tú me llevaste al norte" },
            { time: 128, text: "Rompiste mis esquemas, rompiste el soporte." },
            { time: 132, text: "No sé qué capítulo es, ni cómo termina" },
            { time: 136, text: "Pero es mi favorito si tú eres la heroína." },
            { time: 140, text: "" },
            { time: 142, text: "[Bridge]" },
            { time: 144, text: "Y si alguien pregunta de qué trata mi historia" },
            { time: 148, text: "Les digo que olviden mi vieja memoria." },
            { time: 152, text: "Que la historia empieza..." },
            { time: 156, text: "Justo cuando tú dices \"Hola\"." },
            { time: 160, text: "" },
            { time: 162, text: "[Solo de Guitarra]" },
            { time: 170, text: "" },
            { time: 172, text: "[Chorus Final]" },
            { time: 174, text: "¡Porque no sigo el guion!" },
            { time: 178, text: "Me hiciste un plot twist en el corazón." },
            { time: 182, text: "Yo iba para el sur y tú me llevaste al norte" },
            { time: 186, text: "Rompiste mis esquemas, rompiste el soporte." },
            { time: 190, text: "¡Quédate en la historia, no tenga final!" },
            { time: 194, text: "Contigo lo normal se vuelve genial." },
            { time: 198, text: "" },
            { time: 200, text: "[Outro]" },
            { time: 202, text: "Fuera de guion." },
            { time: 206, text: "Tú y yo." },
            { time: 210, text: "Mucho mejor así." },
            { time: 214, text: "♪" }
        ],
        memories: []
    },
    {
        id: 4,
        title: "One less lonely girl",
        artist: "Cover - Justin Bieber",
        type: "Cover",
        audioUrl: "audio/One less lonely girl.wav",
        coverImage: "portada/One less lonely girl.png",
        coverGradient: "from-purple-400 via-pink-500 to-red-500",
        dedication: "A veces pensamos que la soledad es un vacío, cuando en realidad es el espacio que la vida reserva para quien de verdad sabrá llenarlo. Sé que hubo historias antes, \"start overs\" y lágrimas que no debieron caer. Pero elegí cantarte esto para hacerte una promesa tangible: mientras dependa de mí, la soledad será solo un recuerdo borroso. Entre tantas opciones y ruido allá afuera, mis ojos decidieron enfocarse en una sola variable. Tú eres mi elección consciente para que, en este mundo, haya una chica solitaria menos y un amor verdadero más.",
        emoji: "💜",
        description: "Capítulo 4: One less lonely girl",
        lyrics: [
            { time: 0, text: "♪" },
            { time: 5, text: "[Verse 1]" },
            { time: 8, text: "How many I told you's and start overs and shoulders have you cried on before?" },
            { time: 15, text: "How many promises, be honest girl, how many tears you let hit the floor?" },
            { time: 22, text: "How many bags you packed, just to take them back, tell me that, how many either ors?" },
            { time: 29, text: "But no more if you let me inside of your world, there'll be one less lonely girl" },
            { time: 36, text: "" },
            { time: 37, text: "[Pre-Chorus]" },
            { time: 38, text: "Oh, no, saw so many pretty faces" },
            { time: 43, text: "Now all I see is you" },
            { time: 46, text: "No, no, no, don't need these other pretty faces" },
            { time: 51, text: "And when you're mine in the world, there's gonna be one less lonely girl" },
            { time: 58, text: "" },
            { time: 59, text: "[Chorus]" },
            { time: 60, text: "One less lonely girl" },
            { time: 64, text: "One less lonely girl" },
            { time: 68, text: "One less lonely girl" },
            { time: 72, text: "♪" }
        ],
        memories: []
    }
];
